SELECT * FROM HOSPITAL_COPIA
SELECT * FROM HOSP_OFICIAL
SELECT * FROM HOSPITAL
SELECT * FROM CID_10_CATEGORIAS
SELECT * FROM CID_10_SUBCATEGORIAS

SELECT * FROM carater_atendimento
SELECT * FROM Tipo_internacao
SELECT * FROM motivo_encerramento

UPDATE HOSPITAL_COPIA
SET
    CD_CARATER_ATENDIMENTO = carater_atendimento.Termo
FROM
    HOSPITAL_COPIA
INNER JOIN 
    carater_atendimento ON HOSPITAL_COPIA.CD_CARATER_ATENDIMENTO = carater_atendimento.Código_do_Termo; 


ALTER TABLE HOSPITAL_COPIA
	ALTER COLUMN CD_MOTIVO_SAIDA VARCHAR(100);


SELECT * FROM HOSPITAL_COPIA
ALTER TABLE HOSPITAL_COPIA ADD DS_CID_1 VARCHAR(255);
ALTER TABLE HOSPITAL_COPIA ADD DS_CID_2 VARCHAR(255);
ALTER TABLE HOSPITAL_COPIA ADD DS_CID_3 VARCHAR(255);
ALTER TABLE HOSPITAL_COPIA ADD DS_CID_4 VARCHAR(255);


UPDATE T
SET T.DS_CID_1 = COALESCE(
    SubCat.DESCRICAO, 
    Cat.DESCRICAO    
)
FROM HOSPITAL_COPIA T
LEFT JOIN CID_10_SUBCATEGORIAS SubCat
    ON T.CID_1 = SubCat.SUBCAT
LEFT JOIN CID_10_CATEGORIAS Cat
    ON LEFT(T.CID_1, 3) = Cat.CAT 
WHERE T.CID_1 IS NOT NULL; 

UPDATE T
SET T.DS_CID_2 = COALESCE(
    SubCat.DESCRICAO,
    Cat.DESCRICAO
)
FROM HOSPITAL_COPIA T
LEFT JOIN CID_10_SUBCATEGORIAS SubCat
    ON T.CID_2 = SubCat.SUBCAT
LEFT JOIN CID_10_CATEGORIAS Cat
    ON LEFT(T.CID_2, 3) = Cat.CAT
WHERE T.CID_2 IS NOT NULL;

UPDATE T
SET T.DS_CID_3 = COALESCE(
    SubCat.DESCRICAO,
    Cat.DESCRICAO
)
FROM HOSPITAL_COPIA T
LEFT JOIN CID_10_SUBCATEGORIAS SubCat
    ON T.CID_3 = SubCat.SUBCAT
LEFT JOIN CID_10_CATEGORIAS Cat
    ON LEFT(T.CID_3, 3) = Cat.CAT
WHERE T.CID_3 IS NOT NULL;

UPDATE T
SET T.DS_CID_4 = COALESCE(
    SubCat.DESCRICAO,
    Cat.DESCRICAO
)
FROM HOSPITAL_COPIA T
LEFT JOIN CID_10_SUBCATEGORIAS SubCat
    ON T.CID_4 = SubCat.SUBCAT
LEFT JOIN CID_10_CATEGORIAS Cat
    ON LEFT(T.CID_4, 3) = Cat.CAT
WHERE T.CID_4 IS NOT NULL;







    
UPDATE HOSP_OFICIAL
SET
    CID_1 = HOSPITAL_COPIA.DS_CID_1,
    CID_2 = HOSPITAL_COPIA.DS_CID_2,
    CID_3 = HOSPITAL_COPIA.DS_CID_3,
    CID_4 = HOSPITAL_COPIA.DS_CID_4,
    CARATER_ATENDIMENTO = HOSPITAL_COPIA.CD_CARATER_ATENDIMENTO,
    TIPO_INTERNACAO = HOSPITAL_COPIA.CD_TIPO_INTERNACAO,
    REGIME_INTERNACAO = HOSPITAL_COPIA.CD_REGIME_INTERNACAO,
    MOTIVO_SAIDA = HOSPITAL_COPIA.CD_MOTIVO_SAIDA
FROM
    HOSP_OFICIAL
INNER JOIN 
    HOSPITAL_COPIA ON HOSPITAL_COPIA.ID_EVENTO_ATENCAO_SAUDE = HOSP_OFICIAL.ID_EVENTO AND HOSPITAL_COPIA.ID_PLANO = HOSP_OFICIAL.ID_PLANO;


SELECT * FROM HOSP_OFICIAL
SELECT * FROM HOSPITAL_COPIA

ALTER TABLE HOSP_OFICIAL ALTER COLUMN CID_1 VARCHAR(255) NULL;
ALTER TABLE HOSP_OFICIAL ALTER COLUMN CID_2 VARCHAR(255) NULL;
ALTER TABLE HOSP_OFICIAL ALTER COLUMN CID_3 VARCHAR(255) NULL;
ALTER TABLE HOSP_OFICIAL ALTER COLUMN CID_4 VARCHAR(255) NULL;

ALTER TABLE HOSP_OFICIAL ALTER COLUMN MOTIVO_SAIDA VARCHAR(150);
ALTER TABLE HOSP_OFICIAL ALTER COLUMN REGIME_INTERNACAO VARCHAR(100);
ALTER TABLE HOSP_OFICIAL ALTER COLUMN TIPO_INTERNACAO VARCHAR(100);
ALTER TABLE HOSP_OFICIAL ALTER COLUMN CARATER_ATENDIMENTO VARCHAR(100);


