SELECT * FROM HOSPITAL_COPIA
SELECT * FROM HOSP_OFICIAL
SELECT * FROM HOSPITAL
SELECT * FROM CID_10_CATEGORIAS

SELECT * FROM carater_atendimento
SELECT * FROM Tipo_internacao
SELECT * FROM motivo_encerramento

UPDATE HOSPITAL_COPIA
SET
    CD_CARATER_ATENDIMENTO = carater_atendimento.Termo
FROM
    HOSPITAL_COPIA
INNER JOIN 
    carater_atendimento ON HOSPITAL_COPIA.CD_CARATER_ATENDIMENTO = carater_atendimento.Código_do_Termo; 


ALTER TABLE HOSPITAL_COPIA
	ALTER COLUMN CD_MOTIVO_SAIDA VARCHAR(100);













    
UPDATE HOSPITAL_COPIA
SET
    CD_CARATER_ATENDIMENTO = HOSPITAL.CD_CARATER_ATENDIMENTO
FROM
    HOSPITAL_COPIA
INNER JOIN 
    HOSPITAL ON HOSPITAL_COPIA.ID_EVENTO_ATENCAO_SAUDE = HOSPITAL.ID_EVENTO_ATENCAO_SAUDE AND HOSPITAL_COPIA.ID_PLANO = HOSPITAL.ID_PLANO;
