
SELECT
    h.CD_MUNICIPIO_BENEFICIARIO,
    m1.MUNICÍPIO_IBGE AS MUNICIPIO_BENEFICIARIO,
    h.CD_MUNICIPIO_PRESTADOR,
    m2.MUNICÍPIO_IBGE AS MUNICIPIO_PRESTADOR
FROM HOSPITAL h
INNER JOIN MUNICIPIOS m1
    ON LEFT(CAST(m1.CÓDIGO_DO_MUNICÍPIO_IBGE AS INT), 6) = CAST(h.CD_MUNICIPIO_BENEFICIARIO AS INT)
INNER JOIN MUNICIPIOS m2
    ON LEFT(CAST(m2.CÓDIGO_DO_MUNICÍPIO_IBGE AS INT), 6) = CAST(h.CD_MUNICIPIO_PRESTADOR AS INT);





SELECT * FROM MUNICIPIOS
WHERE CAST(CÓDIGO_DO_MUNICÍPIO_IBGE AS VARCHAR(20)) LIKE '29063%';


SELECT
    h.*,
    m1.MUNICÍPIO_IBGE AS NOME_MUNICIPIO_BENEFICIARIO,
    m2.MUNICÍPIO_IBGE AS NOME_MUNICIPIO_PRESTADOR
INTO HOSPITAL_OFICIAL
FROM HOSPITAL h
INNER JOIN MUNICIPIOS m1
    ON RIGHT(CAST(m1.CÓDIGO_DO_MUNICÍPIO_IBGE AS VARCHAR(7)), 6) = RIGHT(CAST(h.CD_MUNICIPIO_BENEFICIARIO AS VARCHAR(7)), 6)
INNER JOIN MUNICIPIOS m2
    ON RIGHT(CAST(m2.CÓDIGO_DO_MUNICÍPIO_IBGE AS VARCHAR(7)), 6) = RIGHT(CAST(h.CD_MUNICIPIO_PRESTADOR AS VARCHAR(7)), 6);




SELECT TOP 10 *
FROM HOSPITAL_OFICIAL;


SELECT * FROM HOSP_OFICIAL
WHERE CAST(ID_EVENTO_ATENCAO_SAUDE AS VARCHAR(20)) LIKE '5517667471%';


LEFT(CAST(m1.CÓDIGO_DO_MUNICÍPIO_IBGE AS INT), 6)

304234

