
CREATE TABLE HOSP_OFICIAL(
	ID_EVENTO INT NOT NULL,
	ID_PLANO INT NOT NULL,
	SEXO VARCHAR(20) NOT NULL,
	FAIXA_ETARIA VARCHAR(20) NOT NULL,
	PORTE VARCHAR(20) NOT NULL,
	MUNICIPIO_BENEFICIARIO VARCHAR(40) NOT NULL,
	MUNICIPIO_PRESTADOR VARCHAR(40) NOT NULL,
	ESTADO_PRESTADOR VARCHAR(10) NOT NULL,
	MODALIDADE VARCHAR(40) NOT NULL,
	TEMPO_PERMANENCIA INT NOT NULL,
	ANO_MES_EVENTO DATE NOT NULL,
	CARATER_ATENDIMENTO VARCHAR(40) NOT NULL,
	TIPO_INTERNACAO VARCHAR(40) NOT NULL,
	REGIME_INTERNACAO VARCHAR(40) NOT NULL,
	MOTIVO_SAIDA VARCHAR(40) NOT NULL,
	CID_1 VARCHAR(40) NOT NULL,
	CID_2 VARCHAR(40) NOT NULL,
	CID_3 VARCHAR(40) NOT NULL,
	CID_4 VARCHAR(40) NOT NULL,

	PRIMARY KEY(ID_EVENTO, ID_PLANO)
);


/*
mudar tipo
*/
ALTER TABLE HOSP_OFICIAL
ALTER COLUMN ID_EVENTO BIGINT;


ALTER TABLE HOSP_OFICIAL
DROP CONSTRAINT PK__HOSP_OFI__F62DFD4790422870;

ALTER TABLE HOSP_OFICIAL
ADD CONSTRAINT PK__HOSP_OFI__F62DFD4790422870 PRIMARY KEY (ID_EVENTO, ID_PLANO);




ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN ID_EVENTO BIGINT NOT NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN SEXO VARCHAR(20) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN FAIXA_ETARIA VARCHAR(20) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN PORTE VARCHAR(20) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN MUNICIPIO_BENEFICIARIO VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN MUNICIPIO_PRESTADOR VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN ESTADO_PRESTADOR VARCHAR(10) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN MODALIDADE VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN TEMPO_PERMANENCIA INT NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN ANO_MES_EVENTO DATE NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN CARATER_ATENDIMENTO VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN TIPO_INTERNACAO VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN REGIME_INTERNACAO VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN MOTIVO_SAIDA VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN CID_1 VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN CID_2 VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN CID_3 VARCHAR(40) NULL;

ALTER TABLE HOSP_OFICIAL
	ALTER COLUMN CID_4 VARCHAR(40) NULL;



ALTER TABLE HOSP_OFICIAL
ALTER COLUMN ANO_MES_EVENTO VARCHAR(20);



SELECT * FROM HOSP_OFICIAL



INSERT INTO HOSP_OFICIAL (ID_EVENTO, ID_PLANO)
SELECT ID_EVENTO_ATENCAO_SAUDE, ID_PLANO
FROM HOSPITAL;




UPDATE HOSP_OFICIAL
SET
    SEXO = HOSPITAL.SEXO,
    FAIXA_ETARIA = HOSPITAL.FAIXA_ETARIA
FROM
    HOSP_OFICIAL
INNER JOIN 
    HOSPITAL ON HOSP_OFICIAL.ID_EVENTO = HOSPITAL.ID_EVENTO_ATENCAO_SAUDE AND HOSP_OFICIAL.ID_PLANO = HOSPITAL.ID_PLANO;


UPDATE HOSP_OFICIAL
SET
    PORTE = HOSPITAL.PORTE,
	MODALIDADE = HOSPITAL.NM_MODALIDADE,
	TEMPO_PERMANENCIA = HOSPITAL.TEMPO_DE_PERMANENCIA,
	ANO_MES_EVENTO = HOSPITAL.ANO_MES_EVENTO,
    FAIXA_ETARIA = HOSPITAL.FAIXA_ETARIA
FROM
    HOSP_OFICIAL
INNER JOIN 
    HOSPITAL ON HOSP_OFICIAL.ID_EVENTO = HOSPITAL.ID_EVENTO_ATENCAO_SAUDE AND HOSP_OFICIAL.ID_PLANO = HOSPITAL.ID_PLANO;



UPDATE HOSPITAL_COPIA
SET
    CD_CARATER_ATENDIMENTO = HOSPITAL.CD_CARATER_ATENDIMENTO
FROM
    HOSPITAL_COPIA
INNER JOIN 
    HOSPITAL ON HOSPITAL_COPIA.ID_EVENTO_ATENCAO_SAUDE = HOSPITAL.ID_EVENTO_ATENCAO_SAUDE AND HOSPITAL_COPIA.ID_PLANO = HOSPITAL.ID_PLANO;


ALTER TABLE HOSPITAL_COPIA
	ALTER COLUMN CD_MUNICIPIO_PRESTADOR VARCHAR(40);


UPDATE HOSP_OFICIAL
SET
    MUNICIPIO_BENEFICIARIO = HOSPITAL_COPIA.CD_MUNICIPIO_BENEFICIARIO,
	MUNICIPIO_PRESTADOR = HOSPITAL_COPIA.CD_MUNICIPIO_PRESTADOR,
	ESTADO_PRESTADOR = HOSPITAL_COPIA.UF_PRESTADOR
FROM
    HOSP_OFICIAL
INNER JOIN 
    HOSPITAL_COPIA ON HOSP_OFICIAL.ID_EVENTO = HOSPITAL_COPIA.ID_EVENTO_ATENCAO_SAUDE AND HOSP_OFICIAL.ID_PLANO = HOSPITAL_COPIA.ID_PLANO;









SELECT * FROM HOSP_OFICIAL
WHERE CAST(ID_EVENTO AS VARCHAR(20)) LIKE '5517667471%';

SELECT * FROM MUNICIPIOS
SELECT * FROM HOSP_OFICIAL
SELECT * FROM HOSPITAL
SELECT * FROM HOSPITAL_COPIA